#!/usr/bin/env bash
# This will configure Nginx so that its HTTP response contains a custom header.

sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i "25i add_header X-Served-By \$HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
