#!/usr/bin/env bash
# This will configure Nginx so that its HTTP response contains a custom header.

sudo apt-get update -y
sudo apt-get install nginx -y
custom="\\\n\tadd_header X-Served-By $HOSTNAME;\n"
sudo sed -i "74i $custom" /etc/nginx/sites-available/default
sudo service nginx restart
