#!/usr/bin/env bash
#  This is a Bash script that displays To infinity and beyond indefinitely.
#  This traps SIGTERM signal and replaces it with "I am invincible!!!"

trap "echo I am invincible!!!" SIGTERM

while true
do
      echo "To infinity and beyond"
      sleep 2
done
