#!/usr/bin/env bash
#  This script displays numbers from 1 to 20 with superstitious messages

counter=1
while [ $counter -le 20 ]
do
      if [ $counter -eq 4 ]
      then
	  echo "$counter"
	  echo "bad luck from China"
      elif [ $counter -eq 9 ]
      then
	  echo "$counter"
	  echo "bad luck from Japan"
      elif [ $counter -eq 17 ]
      then
	  echo "$counter"
	  echo "bad luck from Italy"
      else
	echo "$counter"
      fi
      ((counter++))
done
