#!/usr/bin/env bash
# This is a Bash script that displays the content of the current directory list
# format where only the part of the name after the first dash is displayed

# * means current directory in bash script

for f in *
do
	echo "$f" | cut -d "-" -f2
done
