#!/usr/bin/env bash
#  This is a script that gives you information about the holbertonschool file.

file="holbertonschool"

if [ -e "$file" ]
then
	echo "$file file exists"
	if [ ! -s "$file" ]
	then
		echo "$file file is empty"
	else
		echo "$file file is not empty"
	fi

	if [ -f "$file" ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "$file file does not exist"
fi
