#!/usr/bin/env bash
# This script installs Nginx and redirects you to 301 Moved Perm.
sudo apt-get update -y

sudo apt-get install nginx -y

sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html

new_string="location /redirect_me {rewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}"

sudo sed -i "30i $new_string" /etc/nginx/sites-available/default

sudo service nginx restart
