#!/usr/bin/env bash
# This is a Bash script that configures Ubuntu server to change it's home ip.
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2 ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
